image: node:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - deploy

variables: 
  CI: ''


pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv public old_public
    - mv build public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "public"